theme: jekyll-theme-architect
title: "Geospatial Analytics using R and R-INLA" 
description: "Instructions, Timetable and Material for the short course at AIMS-Rwanda, 
27 November - 1 December 2023" 
