theme: jekyll-theme-architect
title: "Bayesian modelling for Spatial and Spatio-Temporal data" 
description: "Material for the MSc in Epidemiology module at Imperial College London, 
January-March 2023" 
