theme: jekyll-theme-architect
title: "Bayesian Reasoning and Methods for spatio-temporal data (MSc Epi) - Advanced Analytics (MSc HDA)" 
description: "Instructions, Timetable and Material for the module, 
January - March 2024" 
